swagger: "2.0"
info:
  version: "0.0.1"
  title: Quiz service
  description: Http based microservice for quizzes
# during dev, should point to your local machine
host: localhost:10000
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /questionBanks:
    x-swagger-router-controller: questionBankController
    post:
      description: Desc
      operationId: add
      parameters:
        - name: questionBank
          in: body
          schema:
            $ref: "#/definitions/QuestionBank"
      responses:
        default:
          description: Success
          schema:
            $ref: "#/definitions/QuestionBank"
  /questionBanks/{identifier}:
    x-swagger-router-controller: questionBankController
    get:
      description: Get question bank by identifier
      operationId: getByIdentifier
      parameters:
        - name: identifier
          in: path
          description: Id of question bank to retrieve
          required: true
          type: string
      responses:
        "404":
          description: Question bank not found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Success
          schema:
            $ref: "#/definitions/QuestionBank"
    delete:
      description: Delete question bank by identifier
      operationId: deleteByIdentifier
      parameters:
        - name: identifier
          in: path
          description: Identifier to delete
          required: true
          type: string
      responses:
        "404":
          description: Question bank not found
          schema:
            $ref: "#/definitions/ErrorResponse"
        "200":
          description: Success
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  QuestionBank:
    required:
      - identifier
    properties:
      identifier:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
